var foodItems = {
    "coffee": { wft: 140, unit: "liters per CUP" },
    "tea": { wft: 35, unit: "liters per CUP" },
    "rice": { wft: 3250, unit: "liters per KG" },
    "wheat": { wft: 1500, unit: "liters per KG" },
    "milk": { wft: 1000, unit: "liters per Liter" },
    "eggs": { wft: 135, unit: "liters per EGG" },
    "chicken": { wft: 4100, unit: "liters per KG" },
    "tomatoes": { wft: 300, unit: "liters per KG" },
    "potatoes": { wft: 350, unit: "liters per KG" },
    "onions": { wft: 250, unit: "liters per KG" },
    "lentils": { wft: 4250, unit: "liters per KG" },
    "razor": { wft: 20, unit: "liters" },
    "corn": { wft: 170, unit: "liters per 300gms" },
    "sunglasses": { wft: 40, unit: "liters" },
    "pen": { wft: 2, unit: "liters" },
    "ruler": { wft: 5, unit: "liters" },
    "pizza": { wft: 85, unit: "liters" },
    "bubble gum": { wft: 15, unit: "liters" },
    "biscuit": { wft: 15, unit: "liters per pc" },
    "shampoo": { wft: 150, unit: "liters per 250ml" },
    "jar": { wft: 20, unit: "liters" },
    "lighter": { wft: 15, unit: "liters" },
    "chocolate": { wft: 1100, unit: "liters per BAR" },
    "paper": { wft: 1.5, unit: "liters per pc   " },
    "mirror": { wft: 10, unit: "liters" },
    "straws": { wft: 10, unit: "liters per 10pcs" },
    "shoes": { wft: 8000, unit: "liters" },
    "leather shoes": { wft: 10000, unit: "liters" },
    "laptop": { wft: 40000, unit: "liters" },
    "comb": { wft: 5, unit: "liters" },
    "car": { wft: 800000, unit: "liters" },
    "belt": { wft: 1000, unit: "liters" },
    "wallet": { wft: 800, unit: "liters" },
    "spoon": { wft: 2, unit: "liters" },
    "jacket": { wft: 12000, unit: "liters" },
    "fork": { wft: 2, unit: "liters" },
    "handbag": { wft: 7000, unit: "liters" },
    "knife": { wft: 2, unit: "liters" },
    "fuel": { wft: 47, unit: "liters per gallon" },
    "gasoline": { wft: 50, unit: "liters per gallon" },
    "noodles": { wft: 300, unit: "liters" },
    "apple": { wft: 70, unit: "liters" },
    "banana": { wft: 79, unit: "liters" },
    "egg": { wft: 196, unit: "liters" },
    "potato": { wft: 25, unit: "liters" },
    "tomato": { wft: 13, unit: "liters" },
    "shirt": { wft: 2700, unit: "liters" },
    "jeans": { wft: 7600, unit: "liters" },
    "mobile": { wft: 12000, unit: "liters" },
    "toothbrush": { wft: 5, unit: "liters" },
    "bottle": { wft: 5, unit: "liters" },
}; 